version: '3'

services:
  web:
    build: .
    entrypoint: /code/entrypoint.sh
    env_file:
      - .env.prod
    depends_on:
      - db

#  nginx:
#    restart: always
#    build: ./nginx/
#    ports:
#      - "80:80"
#    volumes:
#      - web-static:/www/static
#    links:
#      - web:web
#
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    expose:
      - "5432"

#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data/
#
#  redis:
#    restart: always
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - redisdata:/data

#volumes:
#  web-django:
#  web-static:
#  pgdata:
#  redisdata: